# Generated by Django 3.2.15 on 2022-08-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('markdown_content', models.TextField()),
            ],
        ),
    ]
