# Generated by Django 3.2.15 on 2022-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(default=''),
        ),
    ]
